## Numpy

Numpy as Numeric python is the foundational open source library for scientific computing , data science and machine learing in python

##### NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.


numpy install - pip install numpy


once NumPy is installed, import it in your applications by adding the **import** keyword:

**import numpy**

NumPy is usually imported under the np alias.

**import numpy as np**

#### Create array using numpy

#### 1. 1D Array(Vectors) - A falt list of numbers

In [7]:
#numPy is used to work with arrays. The array object in NumPy is called ndarray

import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [9]:
#convert to 1D to 2D
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)   #1row and 5 column

array([[1, 2, 3, 4, 5]])

**shape** is an attribute that tells you the dimensions of your array. It returns a tuple of integers showing the size of the array along each axis.

In [11]:
arr3 = np.array([[1, 2, 3, 4, 5]])
arr3.shape

(1, 5)

#### 2D Array(Matrics) - a grid with rowa and column like spreadsheet

In [13]:
arr3 = np.array([[1, 2, 3, 4, 5],[2,3,4,5,6]])
print(arr3)
arr3.shape

[[1 2 3 4 5]
 [2 3 4 5 6]]


(2, 5)

 **Arange** - np.arange() is a built-in function used to create an array containing evenly spaced values within a specified numerical range.

SYNATX - np.arrange(start, stop, step)

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [18]:
np.arange(0,10,2).reshape(5,1)  # 5row 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

**np.ones()** is the built-in function used to create a new array filled entirely with the number 1.

    SYNTAX - np.ones(shape, dtype = None)

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

**identtiy matrix** - you can create an identity matrix using either np.eye() or np.identity().

In [25]:
np.eye(3) ## 3 column 3 row

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Attribute of Numpy Array**

In [30]:
import numpy as np

# Create an array named 'arr'
arr = np.array([[1,2,3,4 ],[2,3,4,5]])
print(arr)

# 1. Check dimensions
print(arr.ndim)   

# 2. Check layout layout
print(arr.shape)  #2 row 4 column

# 3. Check data type
print(arr.dtype) 

# 4. Check total item count
print(arr.size)  


[[1 2 3 4]
 [2 3 4 5]]
2
(2, 4)
int64
8


**Numpy Vectorized operation**

In [31]:
arr1 = np.array([1,2,3,4,5])
arr2= np.array([10,20,30,40,50])

## element with addition
print("Addition" , arr1+arr2)

## element wise subtraction
print("Subtraction" , arr1-arr2)

Addition [11 22 33 44 55]
Subtraction [ -9 -18 -27 -36 -45]


**Universal function**

In [32]:
arr = np.array([2,3,4,5,6])
## square root

print(np.sqrt(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]


In [33]:
#exponential
print(np.exp(arr))

[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]


In [34]:
#sine
print(np.sin(arr))

[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]


**Slicing and indexing**

In [37]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,2],[3,5,2,1,5]])
print("Array: ",arr)

Array:  [[1 2 3 4 5]
 [6 7 8 9 2]
 [3 5 2 1 5]]


In [38]:
arr[0]

array([1, 2, 3, 4, 5])

In [39]:
arr[0][2]

np.int64(3)

In [46]:
arr[1:,2:]

array([[8, 9, 2],
       [2, 1, 5]])

In [47]:
## modify array element

arr[0][0] =100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9   2]
 [  3   5   2   1   5]]


**Normalization**

In [48]:
data = np.array([1,2,3,4,5])

mean = np.mean(data)
std_dev = np.std(data)

norm_data= (data-mean)/std_dev
print("Normalized data", norm_data)

Normalized data [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### Array Types and conversion between types

In [49]:
import numpy as np
integer = np.array([10,20,30,40,50])
print(integer)

[10 20 30 40 50]


In [50]:
integer[0]

np.int64(10)

In [51]:
integer[0]= 21.2
integer

array([21, 20, 30, 40, 50])

In [52]:
integer.dtype

dtype('int64')

In [54]:
smallerInt = np.array(integer, dtype = np.int8)
smallerInt

array([21, 20, 30, 40, 50], dtype=int8)

In [55]:
integer.nbytes

40

In [56]:
smallerInt.nbytes

5

In [57]:
overflow=np.array([127,128,129])
overflow

array([127, 128, 129])

### Multidimensional array

In [58]:
nums = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [59]:
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [60]:
nums[0,0]

np.int64(1)

In [61]:
nums[1,4]

np.int64(10)

In [62]:
nums.ndim

2

### Creating array from List and other Python Strucures


In [63]:
import numpy as np
first_list =[1,2,3,4,5,6,7,8,9]
first_list

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [64]:
first_arr = np.array(first_list)
first_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
list2 = ['Ann', 11111,'peter',1112,

### Instrisic Numpy array creation

In [2]:
import numpy as np

integer = np.array(10)
integer =np.arange(10)
integer

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
second = np.arange(100,120)
second

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119])

In [4]:
third = np.arange(100,150, 3)
third

array([100, 103, 106, 109, 112, 115, 118, 121, 124, 127, 130, 133, 136,
       139, 142, 145, 148])

**numpy.linspace()** is a tool in Python used to create a list of numbers that are evenly spaced apart within a specific range

In [6]:
first_floats = np.linspace(10,20)
first_floats

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [8]:
second_float = np.linspace(10,20,3)
second_float

array([10., 15., 20.])

**numpy.random** module is a built-in toolkit used to generate random numbers, shuffle data, and simulate chance.

In [9]:
first_random = np.random.rand(10)
first_random

array([0.43992817, 0.80911297, 0.40906336, 0.66542833, 0.88825709,
       0.31271531, 0.31132172, 0.54252628, 0.32426223, 0.27205711])

In [13]:
rnd_int = np.random.randint(0,20,5)
rnd_int

array([10, 17,  9, 10,  9], dtype=int32)

### Creating arrays filled with constnt values

In [14]:
import numpy as np

first_array = np.zeros(5)
first_array

array([0., 0., 0., 0., 0.])

In [16]:
second = np.zeros((2,3))
second

array([[0., 0., 0.],
       [0., 0., 0.]])

**np.ones()** is the built-in function used to create a new array filled entirely with the number 1.

SYNTAX - np.ones(shape, dtype = None)

In [17]:
first_one = np.ones(6)
first_one

array([1., 1., 1., 1., 1., 1.])

In [19]:
second_one = np.ones((2,4))
second_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
third_one = np.ones((4,5), dtype=int)
third_one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**numpy.fill()** is a built-in tool used to replace every single item in an existing array with one specific value.

syntax- syntax- array_name.fill(value)

In [25]:
import numpy as np

# Create a 2x3 grid of numbers
grid = np.array([[1, 2, 3], [4, 5, 6]])
print("Original:\n", grid)

# Fill it completely with zeros
grid.fill(0)
print("\nAfter fill:\n", grid)



Original:
 [[1 2 3]
 [4 5 6]]

After fill:
 [[0 0 0]
 [0 0 0]]


**numpy.empty()** is a tool used to create a brand-new array instantly without setting any initial values.

SYNTX - 
np.empty(shape, dtype=float)

In [26]:
import numpy as np

# Create a blank space for 3 decimals
garbage_array = np.empty(3)
print(garbage_array)

[10. 15. 20.]


**numpy.full()** is a built-in tool used to create a brand-new array of any size where every single slot is automatically filled with a value you choose.

np.full(shape, fill_value, dtype=None)

In [1]:
import numpy as np

lucky_sevens = np.full(5, 7)
print(lucky_sevens)

[7 7 7 7 7]


In [28]:
import numpy as np

pi_grid = np.full((2, 4), 3.14)
print(pi_grid)

[[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]


In [29]:
import numpy as np

status_lights = np.full(3, "OFF")
print(status_lights)

['OFF' 'OFF' 'OFF']


### Finding the shape and size of the array

In [2]:
import numpy as np

first = np.arange(20)
first


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [3]:
second = np.linspace((1,2),(10,20),10)
second


array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.],
       [ 6., 12.],
       [ 7., 14.],
       [ 8., 16.],
       [ 9., 18.],
       [10., 20.]])

In [4]:
third = np.full((2,2,2,),10)
third

array([[[10, 10],
        [10, 10]],

       [[10, 10],
        [10, 10]]])

In [5]:
np.shape(first)

(20,)

In [6]:
np.shape(second)

(10, 2)

In [7]:
np.shape(third)

(2, 2, 2)

### Adding , removing and sorting elemnt


In [8]:
import numpy as np

first = np.array([1,2,3,4,5])
first

array([1, 2, 3, 4, 5])

In [10]:
new_first = np.insert(first,3, 10)
new_first

array([ 1,  2,  3, 10,  4,  5])

In [12]:
second = np.array([1,3,4])
second

array([1, 3, 4])

In [14]:
new_second = np.append(second, 5)
new_second

array([1, 3, 4, 5])

In [15]:
third = np.array([1,2,3,4,5])
third

array([1, 2, 3, 4, 5])

In [16]:
new_third = np.delete(third,3)
new_third

array([1, 2, 3, 5])

In [17]:
integer = np.random.randint(0,20,20)
integer

array([19,  2, 10,  9,  4, 18,  7, 16,  4,  3,  0,  6, 15, 17,  9, 16,  5,
       18,  7, 12], dtype=int32)

In [20]:
print(np.sort(integer))

[ 0  2  3  4  4  5  6  7  7  9  9 10 12 15 16 16 17 18 18 19]


In [23]:
twoD_array = np.array([[3,4,2,5,1],[7,4,9,1,0]])
twoD_array

array([[3, 4, 2, 5, 1],
       [7, 4, 9, 1, 0]])

In [24]:
new_2d_array = np.sort(twoD_array)
new_2d_array

array([[1, 2, 3, 4, 5],
       [0, 1, 4, 7, 9]])

In [25]:
colors = np.array(['orange', 'blue', 'yellow', 'cream', 'purple', 'red', 'white'])
colors


array(['orange', 'blue', 'yellow', 'cream', 'purple', 'red', 'white'],
      dtype='<U6')

In [26]:
print(np.sort(colors))

['blue' 'cream' 'orange' 'purple' 'red' 'white' 'yellow']


### Cpy and View in numpy

a copy creates a brand new independent array, while a view is just a window pointing to the original array's data.

1. **Using .view()** (Shared Data)Since a view shares memory with the original array, modifying one will modify both.

In [32]:
original = np.array([1, 2, 3, 4])
arr_view = original.view()

# Modify the view
arr_view[0] = 99

print("Modified View:", arr_view)  
print("Original Array:", original)

Modified View: [99  2  3  4]
Original Array: [99  2  3  4]


2. **Using .copy()** (Independent Data)A copy is a completely separate object in your computer's memory.

In [30]:
original = np.array([1, 2, 3, 4])
arr_copy = original.copy()

# Modify the copy
arr_copy[0] = 99

print("Modified Copy:", arr_copy)  
print("Original Array:", original)

Modified Copy: [99  2  3  4]
Original Array: [1 2 3 4]


**reshape()** function in NumPy allows you to change the shape (dimensions) of an array without changing its actual data.

In [33]:
# Create a 1D array with 6 elements
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape to 2 rows and 3 columns
matrix = arr.reshape(2, 3)

print(matrix)

[[1 2 3]
 [4 5 6]]


### Joining and spitting array

***joining** means combining multiple arrays into a single array, while **splitting** means breaking a single array down into multiple smaller arrays.

In [37]:
import numpy as np

first = np.arange(1,11)
second = np.arange(11,21)
print(f" first array: ", first)
print(" second array:", second)

 first array:  [ 1  2  3  4  5  6  7  8  9 10]
 second array: [11 12 13 14 15 16 17 18 19 20]


In [39]:
con_arr = np.concatenate((first, second))
print("concatenate array", con_arr)

concatenate array [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [42]:
second_d_array = np.array([[1,2,3,4,5],[4,5,6,7,8]])
second_d_array 

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8]])

In [44]:
third_d_array = np.array([[1,2,3,4,5],[3,4,5,6,7]])
third_d_array

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [46]:
con_2array= np.concatenate((second_d_array , third_d_array))
con_2array

array([[1, 2, 3, 4, 5],
       [4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7]])

In [48]:
st_arr = np.stack((first, second))
st_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [49]:
hst_arr = np.hstack((first, second))
hst_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [50]:
vst_arr = np.vstack((first, second))
vst_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [51]:
numbers = np.arange(1,15)
numbers

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [53]:
sp_array = np.array_split(numbers, 4)
sp_array

[array([1, 2, 3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10, 11]),
 array([12, 13, 14])]

### Arithmatic and function of numpy

**Vectorization** - operation can be executed in parallel on multiple eleemnt of the array

In [57]:
import numpy as np

a= np.arange(1,11)
b = np.arange(21,31)
print("a", a)
print("b", b)

a [ 1  2  3  4  5  6  7  8  9 10]
b [21 22 23 24 25 26 27 28 29 30]


In [58]:
a+b

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

In [59]:
b-a

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20])

In [60]:
a/b

array([0.04761905, 0.09090909, 0.13043478, 0.16666667, 0.2       ,
       0.23076923, 0.25925926, 0.28571429, 0.31034483, 0.33333333])

In [61]:
a*b

array([ 21,  44,  69,  96, 125, 156, 189, 224, 261, 300])

**Broadcasting** *is a powerful mechanism in NumPy that allows arithmetic operations between arrays of different shapes

In [62]:
import numpy as np
a= np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
b = np.arange(1,4)
b

array([1, 2, 3])

In [65]:
a+b

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [66]:
c=np.arange(1,3)
c

array([1, 2])

In [67]:
a+c

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [68]:
d =np.arange(24).reshape(2,3,4)
d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [69]:
e= np.arange(4)
e

array([0, 1, 2, 3])

In [70]:
d-e

array([[[ 0,  0,  0,  0],
        [ 4,  4,  4,  4],
        [ 8,  8,  8,  8]],

       [[12, 12, 12, 12],
        [16, 16, 16, 16],
        [20, 20, 20, 20]]])

### Aggregate functions

In [71]:
import numpy as np

first= np.arange(10,110,10)
first


array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [73]:
second = np.arange(10,100,10).reshape(3,3)
second

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [75]:
third = np.arange(10,110,10).reshape(2,5)
third

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

In [77]:
print(first.sum())
print(third.sum())
print(second.sum())

550
550
450


In [78]:
second.sum(axis=0)

array([120, 150, 180])

In [79]:
first.prod()

np.int64(36288000000000000)

In [80]:
np.average(first)

np.float64(55.0)

In [81]:
np.min(first)

np.int64(10)

In [82]:
np.mean(first)

np.float64(55.0)