# Module: NumPy Assignments
## Lesson: NumPy
### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [11]:
#1  -
import numpy as np

data = np.random.randint(1,21, size = (5,5))
data
data[:,2] =1
data

array([[12,  5,  1,  3,  2],
       [18, 14,  1,  9, 14],
       [19,  8,  1,  8, 12],
       [15, 16,  1, 12, 16],
       [ 9,  1,  1, 19,  5]], dtype=int32)

In [19]:
arr = np.arange(1,17).reshape(4,4)
arr

np.fill_diagonal(arr,0)
arr

array([[ 0,  2,  3,  4],
       [ 5,  0,  7,  8],
       [ 9, 10,  0, 12],
       [13, 14, 15,  0]])


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.
2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [39]:
arr2 = np.arange(1,37).reshape(6,6)
print("Original:\n ", arr2)

new_array = arr2[2:5, 1:4]
print('row and coulmn:\n', new_array)



Original:
  [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
row and coulmn:
 [[14 15 16]
 [20 21 22]
 [26 27 28]]


In [46]:
arr = np.random.randint(1,51, size=(5,5))
print(arr)

mask = np.ones((5,5) ,dtype = bool)
mask[1:-1,1:-1 ]= False
border =arr[mask]
border

[[ 4 18 22  9 46]
 [13 22 49 25 11]
 [47 41 35 10 24]
 [12 14 43 32 49]
 [30 30 37  5 42]]


array([ 4, 18, 22,  9, 46, 13, 11, 47, 24, 12, 49, 30, 30, 37,  5, 42],
      dtype=int32)

### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.
2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [11]:
import numpy as np
arr = np.random.randint(1,20, size=(3,4))
arr1= np.random.randint(1,20,size=(3,4))
addition = arr + arr1
subtraction = arr - arr1
multiplication = arr* arr1
division = arr/ arr1

print("Array A:\n", arr)
print("\nArray B:\n", arr1)
print("\nAddition (+):\n", addition)
print("\nSubtraction (-):\n", subtraction)
print("\nMultiplication (*):\n", multiplication)
print("\nDivision (/):\n", division)

Array A:
 [[17 12 15  9]
 [ 4 16 16  4]
 [11  3 13  4]]

Array B:
 [[ 3  4  2 10]
 [13 18  5 11]
 [17  2  4 11]]

Addition (+):
 [[20 16 17 19]
 [17 34 21 15]
 [28  5 17 15]]

Subtraction (-):
 [[14  8 13 -1]
 [-9 -2 11 -7]
 [-6  1  9 -7]]

Multiplication (*):
 [[ 51  48  30  90]
 [ 52 288  80  44]
 [187   6  52  44]]

Division (/):
 [[5.66666667 3.         7.5        0.9       ]
 [0.30769231 0.88888889 3.2        0.36363636]
 [0.64705882 1.5        3.25       0.36363636]]


In [13]:
array = np.arange(1,17).reshape(4,4)
print(array)

row = np.sum(array , axis =0)
column = np.sum(array,axis =1)

print("Row:", row)
print("column:", column)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row: [28 32 36 40]
column: [10 26 42 58]


### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.
2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [19]:
aray = np.random.randint(1,30, size=(5,5))
print("array:",aray)

maen = np.mean(aray)
print("Mean:", maen)

mdm = np.median(aray)
print("Median:", mdm)

stand_vari = np.std(aray)
print("Standard deviation:", stand_vari)

vari = np.var(aray)
print("Variance:", vari)

array: [[ 9 10 27 20 19]
 [17  9  6 18 22]
 [25  8 27 29 22]
 [25 24  7 17 15]
 [ 9 25 20 28 11]]
Mean: 17.96
Median: 19.0
Standard deviation: 7.31836047212762
Variance: 53.5584


In [22]:
arr1 = np.arange(1,10).reshape(3,3)
print(arr1)

mean = np.mean(arr1)
std = np.std(arr1)

norm = (arr1 - mean)/std
print(norm)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.
2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [23]:
import numpy as np

# Create a 3x3 2D array filled with random integers from 1 to 10
matrix_2d = np.random.randint(1, 11, size=(3, 3))

# Create a 1D array of shape (3,)
array_1d = np.array([10, 20, 30])

# Add the 1D array to each row of the 2D array via broadcasting
result = matrix_2d + array_1d

print("Original 2D Matrix (3, 3):\n", matrix_2d)
print("\n1D Array to Add (3,):\n", array_1d)
print("\nResulting Matrix (3, 3):\n", result)


Original 2D Matrix (3, 3):
 [[6 9 8]
 [1 3 8]
 [1 5 1]]

1D Array to Add (3,):
 [10 20 30]

Resulting Matrix (3, 3):
 [[16 29 38]
 [11 23 38]
 [11 25 31]]


In [5]:
import numpy as np

#create a 4x4 2D array filled with random integr from 1 to 13

matrix = np.random.randint(1,13, size=(4,4))

array = np.array([10,20,30,40])

result = array - matrix
print(matrix)


[[ 9 10  5  4]
 [ 8  3  7  7]
 [ 1  1  4 10]
 [ 2  7  9  7]]



### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.
2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [7]:
import numpy as np

# 1. Create a 3x3 NumPy array (Matrix)
matrix = np.array([[4, 2, 1],
                   [1, 3, 0],
                   [2, 1, 5]])

# 2. Compute the determinant
determinant = np.linalg.det(matrix)

# 3. Compute the multiplicative inverse
inverse = np.linalg.inv(matrix)

# 4. Compute the eigenvalues (and eigenvectors)
eigenvalues, eigenvectors = np.linalg.eig(matrix)

# Display results
print("Original 3x3 Matrix:")
print(matrix)
print(f"\nDeterminant: {determinant:.2f}")
print("\nInverse Matrix:")
print(inverse)
print("\nEigenvalues:")
print(eigenvalues)


Original 3x3 Matrix:
[[4 2 1]
 [1 3 0]
 [2 1 5]]

Determinant: 45.00

Inverse Matrix:
[[ 0.33333333 -0.2        -0.06666667]
 [-0.11111111  0.4         0.02222222]
 [-0.11111111  0.          0.22222222]]

Eigenvalues:
[6.33005874 1.87158094 3.79836032]


In [13]:
arr1 = np.array([[1,2,3],
                [4,5,6]])
print("Array1:", arr1)

arr2 = np.array([[1,2],
                 [3,4],
                 [5,6]])
print("Array2:", arr2)


result = arr1 @ arr2
print("Result:", result)

Array1: [[1 2 3]
 [4 5 6]]
Array2: [[1 2]
 [3 4]
 [5 6]]
Result: [[22 28]
 [49 64]]


### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).
2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [20]:
array1 = np.arange(1,10).reshape(3,3)
print("Array1:")
print(array1)

# reshape 1 to 9
row = array1.reshape(1,9)
print("Row:")
print(row)

#reshape 9 to 1
column = array1.reshape(9,1)
print("coulmn;")
print(column)

Array1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Row:
[[1 2 3 4 5 6 7 8 9]]
coulmn;
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [24]:
flt = np.random.randint(1,26, size=(5,5))
print("Original array:")
print(flt)

flt_rray = flt.flatten()
print("Flattern Array:")
print(flt_rray)

rsult = flt_rray.reshape(5,5)
print("Reshape Array:")
print(rsult)

Original array:
[[ 8  7 25 23 16]
 [ 7  6  8 22 11]
 [22  3 15 22 25]
 [ 9  9 17  8 19]
 [ 4  5 23 20  2]]
Flattern Array:
[ 8  7 25 23 16  7  6  8 22 11 22  3 15 22 25  9  9 17  8 19  4  5 23 20
  2]
Reshape Array:
[[ 8  7 25 23 16]
 [ 7  6  8 22 11]
 [22  3 15 22 25]
 [ 9  9 17  8 19]
 [ 4  5 23 20  2]]



### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.
2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [30]:
import numpy as np

# Create the random 5x5 matrix
array1 = np.random.randint(1, 26, size=(5, 5))
print("Array 1:")
print(array1)

# Define row and column indices for fancy indexing
row = [[0],[4]]
column = [[0,4]]

# FIX: Changed parentheses ( ) to square brackets [ ]
corner = array1[row, column]
print("\nCorner of the matrix:")
print(corner)


Array 1:
[[16 25  9 19  1]
 [ 8 14  6 24  7]
 [ 1 18  6 14 20]
 [14  6 12 16 21]
 [24 12 18  4 19]]

Corner of the matrix:
[[16  1]
 [24 19]]


In [34]:
array2 = np.random.randint(1,17, size=(4,4))
print("Array:")
print(array2)

result = array2 <= 10 
print("Boolean:")
print(result)

Array:
[[ 6 16  8 10]
 [ 5 10  8  7]
 [ 6 12  4 14]
 [ 1 16  7 13]]
Boolean:
[[ True False  True  True]
 [ True  True  True  True]
 [ True False  True False]
 [ True False  True False]]


### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.
2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [38]:
dt = np.dtype([('name', 'U20'), ('age', 'i4'), ('weight', 'f4')])

# 2. Add some sample data
data = [
    ('Alice', 25, 55.5),
    ('Bob', 32, 78.2),
    ('Charlie', 19, 68.0),
    ('Diana', 28, 62.1)
]

structured_array = np.array(data, dtype=dt)
print("Original Structured Array:")
print(structured_array)

sorted_array = np.sort(structured_array, order='age')

print("\nSorted Array by Age:")
print(sorted_array)

Original Structured Array:
[('Alice', 25, 55.5) ('Bob', 32, 78.2) ('Charlie', 19, 68. )
 ('Diana', 28, 62.1)]

Sorted Array by Age:
[('Charlie', 19, 68. ) ('Alice', 25, 55.5) ('Diana', 28, 62.1)
 ('Bob', 32, 78.2)]


In [ ]:
# 1. Define the structured array dtype with 'x' and 'y' fields
dt = np.dtype([('x', 'i4'), ('y', 'i4')])

# 2. Add sample points (coordinates)
data = [(1, 2), (4, 6), (7, 2)]
points = np.array(data, dtype=dt)

# 3. Extract individual coordinate arrays
x = points['x']
y = points['y']


### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.
2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.